INSERT INTO public.people (id,"name") VALUES
	 (1,'Christopher Nolan'),
	 (2,'Frank Darabont'),
	 (3,'Anthony Russo'),
	 (4,'James Cameron'),
	 (5,'Peter Jackson'),
	 (6,'Denis Villeneuve'),
	 (7,'Matt Reeves'),
	 (8,'Patty Jenkins'),
	 (9,'Taika Waititi'),
	 (10,'Ridley Scott'),
	 (11,'Timothée Chalamet'),
	 (12,'Zendaya'),
	 (13,'Robert Pattinson'),
	 (14,'Gal Gadot'),
	 (15,'Chris Hemsworth'),
	 (16,'Paul Mescal'),
	 (38,'Jhonny Depp'),
	 (39,'Christian Ce'),
	 (40,'Federus Rudi');
